---
title: "Proposal"
author: "Group3"
date: "11/16/2022"
output: html_document
---

### Background

Ad fraud (or Click Fraud) is concerned with fraudulently representing online advertisement impressions, clicks, conversion, or data events for financial gain. Ad fraud attempt to deceive advertising platforms that fake activity on the network is actual user behavior. App install fraud is one type of ad fraud that may cause high financial exposure. To deal with the problem, we are planning to detect the fack install from the installation records in this project.

### Task
Our task is to predict whether a user will download an app after clicking a mobile app advertisement.

### Data

##### Read Data
```{r}
sampledata <- read.csv(file = 'train_sample.csv')
head(sampledata)
```


##### Variable Description

ip: ip address of click.

app: app id for marketing.

device: device :  id of user mobile phone (e.g., iphone 6 plus, iphone 7, huawei mate 7, etc.) 

os: os version id of user mobile phone 

channel: channel id of mobile ad publisher 

click_time: timestamp of click (UTC) 

attributed_time: if the user downloads the app after clicking an ad, this is the time of the app download 

is_attributed: the target that is to be predicted, indicating the app was downloaded


### Statistical Methods

We are going to summarize the feature of variables based on the descriptive statistics(such as mean and median), then construct models including regression model,support vector machines,  k-Nearest-Neighbor,  random forest, xgboost methods on this data.

### Computational Steps

1. Data preprocessing on the raw data, including date data transformation, handling imbalance data.

2. Exploratory data analysis with visualization.

3. Modeling on the training data.

4. Evaluate and compare the performance of models.


### Github repository
https://github.com/amandazhao2022/STAT605_Project




